[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'ervandew/supertab'

# [[plugins]]
# repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
repo = 'jacquesbh/vim-showmarks'
